<?php $this->extend('/Help/view'); ?>
<?php $this->assign('title', 'Storage cleanup — eQSL Card Help'); ?>
<?php $this->start('meta'); ?>
<meta name="description" content="How to use the eQSL Card admin cleanup page to purge guest cards, prune orphan uploads, and clear caches.">
<?php $this->end(); ?>

<?= $this->element('ui/page_header', [
    'title' => $title,
    'lede'  => 'The cleanup page at /admin/cleanup provides safe, audited maintenance actions to reclaim disk space and clear stale data — with a dry-run preview before anything is deleted.',
]) ?>

<h2>How the page works</h2>
<p>Every section on the cleanup page first shows a <strong>count preview</strong> — how many rows would be affected at the current cutoff — so you can verify the scope before clicking the action button. The cutoff is adjustable via the <strong>Days</strong> slider at the top; the preview updates as you change it.</p>

<?= $this->element('ui/screenshot', [
    'src' => '/files/help/admin/cleanup/overview.webp',
    'alt' => 'The cleanup page showing the days slider, guest-card count, and orphan-upload count',
    'caption' => 'Set the day cutoff and review the preview counts before running any action.',
]) ?>

<h2>Guest-card purge</h2>
<p>Guest cards are generated by anonymous visitors through the public render form. They're temporary by nature — once the visitor has downloaded their card, the server copy isn't needed. <strong>Purge guest cards</strong> deletes guest-owned card rows and their PNG/WebP/PDF files on disk, for cards older than the selected cutoff.</p>

<?= $this->element('ui/callout', [
    'variant' => 'warning',
    'body' => 'Run guest-card purge <em>before</em> orphan-upload prune. The cards-to-uploads foreign key is RESTRICT — uploads attached to guest cards can\'t be pruned until the card row is gone. The recommended order is: Purge guest cards → Expire old cards → Prune orphan uploads.',
]) ?>

<h2>Expire old user cards</h2>
<p>If you've configured a <strong>Card retention (days)</strong> value in <a href="/admin/settings">settings</a>, this section shows how many user-owned cards are past the retention threshold. Click <strong>Expire old cards</strong> to soft-delete them (the <code>deleted_at</code> column is stamped; the physical file is not yet removed). Run <em>Prune orphan uploads</em> afterwards to free disk.</p>
<p>If retention is disabled (set to 0 in settings), this section is shown as informational only — the action button is inactive.</p>

<h2>Orphan-upload prune</h2>
<p>Uploads that no card references anymore are orphans — typically left behind after card deletion, guest purge, or failed renders. <strong>Prune orphan uploads</strong> deletes both the database row and the file on disk for uploads older than the cutoff and with no linked card.</p>

<h2>Callsign cache</h2>
<p>The <code>callsign_lookups</code> table caches callsign lookup results for 90 days. <strong>Clear callsign cache</strong> wipes the entire table — the next lookup for any callsign re-queries the providers. Use this when a provider's data has gone stale or after enabling a new provider with better coverage.</p>

<h2>Application cache</h2>
<p>CakePHP caches models, views, and config under <code>tmp/cache/</code>. <strong>Clear application cache</strong> deletes all files there and calls <code>Cache::clearAll()</code>. Safe to run any time — the cache rebuilds itself on the next request. Useful after a deployment or permission issue causes <em>Permission denied</em> errors on stale cache files.</p>

<h2>Log files</h2>
<p><strong>Clear logs</strong> deletes all <code>.log</code> files under <code>logs/</code>. The file logger reopens its target on the next log write, so no restart is needed. Run this monthly on installs with heavy traffic to prevent the log directory growing unbounded.</p>

<h2>Sessions</h2>
<p><strong>Clear sessions</strong> deletes all active file sessions under <code>tmp/sessions/</code>. This forces every signed-in user — including you — to log in again. The action logs you out immediately after the session files are deleted and redirects to the login page.</p>

<?= $this->element('ui/callout', [
    'variant' => 'warning',
    'body' => 'Clearing sessions is a mass-logout event. Use it as a last resort — for example, after a suspected session fixation attack or when stale sessions are causing unexpected behaviour.',
]) ?>

<h2>Audit trail</h2>
<p>Every cleanup action — purge, prune, cache clear, log clear, session clear — writes a row to the <a href="/admin/audit">audit log</a> with the count of affected items. You can review past cleanup runs there.</p>
