<?php $this->extend('/Help/view'); ?>
<?php $this->assign('title', 'Site settings — eQSL Card Help'); ?>
<?php $this->start('meta'); ?>
<meta name="description" content="Walkthrough of every knob on the eQSL Card admin settings page — SMTP, storage, callsign lookup, and security.">
<?php $this->end(); ?>

<?= $this->element('ui/page_header', [
    'title' => $title,
    'lede'  => 'The settings page at /admin/settings controls SMTP, upload limits, the default card background, callsign auto-complete, and security options.',
]) ?>

<h2>General</h2>
<dl class="row dl-stack">
  <dt class="col-sm-3">Site name</dt>
  <dd class="col-sm-9">Shown in the page title and outbound emails. Defaults to <em>eQSL Card</em>. Change it to match your club or callsign if this is a station-specific install.</dd>

  <dt class="col-sm-3">Share base URL</dt>
  <dd class="col-sm-9">The root URL used to build public share links (<code>https://your-domain/qsl/{slug}</code>). Must include the scheme. Change this if the site lives at a sub-path or uses a CDN URL.</dd>
</dl>

<h2>Uploads</h2>
<dl class="row dl-stack">
  <dt class="col-sm-3">Max upload (MB)</dt>
  <dd class="col-sm-9">Maximum file size accepted for background image uploads, in megabytes. Set to 0 to disable user uploads entirely. Keep this below the PHP <code>upload_max_filesize</code> directive — the PHP limit always wins.</dd>

  <dt class="col-sm-3">Default background</dt>
  <dd class="col-sm-9">The fallback background image used when an operator picks "site default" at render time. Upload an image here (JPEG, PNG, or WebP, max 2000×1500 px after auto-resize). If no custom background is uploaded, the bundled demo image is used. Attribution fields (author, licence) are stored and printed on cards that use this background.</dd>
</dl>

<?= $this->element('ui/screenshot', [
    'src' => '/files/help/admin/settings/background-upload.webp',
    'alt' => 'The default background upload section with a current preview and upload controls',
    'caption' => 'Upload a default background — all operators who pick "site default" use this image.',
]) ?>

<h2>Email (SMTP)</h2>
<p>Configure SMTP to enable password-reset emails. Without SMTP, users who forget their password have no self-service recovery path.</p>
<dl class="row dl-stack">
  <dt class="col-sm-3">SMTP host</dt>
  <dd class="col-sm-9">The mail server hostname, e.g. <code>smtp.mailgun.org</code> or <code>mail.your-isp.com</code>.</dd>

  <dt class="col-sm-3">SMTP port</dt>
  <dd class="col-sm-9">587 for STARTTLS (recommended), 465 for SSL/TLS, 25 for unencrypted (avoid).</dd>

  <dt class="col-sm-3">SMTP user / password</dt>
  <dd class="col-sm-9">Credentials for your mail account. Stored in the database (app_settings table), not in a config file.</dd>

  <dt class="col-sm-3">From address</dt>
  <dd class="col-sm-9">The address that appears in the <em>From</em> field of outbound emails, e.g. <code>noreply@your-domain.com</code>.</dd>
</dl>

<?= $this->element('ui/callout', [
    'variant' => 'tip',
    'body' => 'Use a transactional mail service (Mailgun, Postmark, SES) rather than your ISP\'s SMTP — they provide delivery logs and are less likely to get flagged as spam. Free-tier accounts on most services cover the volume a typical amateur radio site generates.',
]) ?>

<h2>Card credit line</h2>
<dl class="row dl-stack">
  <dt class="col-sm-3">Credit template</dt>
  <dd class="col-sm-9">A free-text string printed as a micro-credit on rendered cards. Supports the placeholder <code>{site_name}</code>. Default: <em>Generated by {site_name}</em>. Set this to your club's name or website.</dd>

  <dt class="col-sm-3">Card retention (days)</dt>
  <dd class="col-sm-9">When set to a positive integer, the <em>Expire old cards</em> action on <a href="/admin/cleanup">/admin/cleanup</a> soft-deletes user cards older than this many days. Set to 0 to disable retention entirely (cards live forever). The soft-delete hides cards from the user's library but doesn't immediately free disk — run <em>Prune orphan uploads</em> after expiry to reclaim space.</dd>
</dl>

<h2>Callsign auto-complete</h2>
<p>See the dedicated article: <a href="/help/logging/autocomplete">Callsign auto-complete</a>. This section summarises the settings pane:</p>
<ul>
  <li>Check <strong>Enable callsign auto-complete</strong> to turn it on.</li>
  <li>Tick each provider you want active and drag them into priority order. The local CSV directory always appears at the top and is always the first provider tried, regardless of drag order.</li>
  <li>A QRZ API key field appears when QRZ is selected.</li>
</ul>

<h2>Security</h2>
<dl class="row dl-stack">
  <dt class="col-sm-3">Bypass rate limit for private IPs</dt>
  <dd class="col-sm-9">When checked, requests from RFC-1918 addresses (10.x, 172.16.x, 192.168.x) and localhost skip the login-rate-limit. Useful for internal testing; harmless on a public internet install since those IPs are never routed.</dd>
</dl>

<h2>Next up</h2>
<p><a href="/help/admin/users">User management</a> covers adding admins and soft-deleting accounts. <a href="/help/admin/cleanup">Storage cleanup</a> describes the periodic maintenance tasks — guest card purge, orphan prune, cache and log clearing.</p>
