<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users ORM table.
 *
 * Associations:
 *   - hasMany Cards       — QSL cards generated by this user.
 *   - hasMany Templates   — card templates owned by this user.
 *   - hasMany CardBackgrounds (FK upload_id) — background images uploaded by this user.
 *
 * The Timestamp behavior stamps created_at on insert and updated_at on every
 * save. Validation enforces unique email, required name + callsign, and an
 * enum role of admin|user. The password field is virtual: writing to it
 * triggers User::_setPassword() which hashes via Argon2id and stores the
 * result in password_hash.
 */
class UsersTable extends Table
{
    /**
     * Configure table name, primary key, Timestamp behavior, and associations.
     *
     * @param array<string, mixed> $config Table config passed from the ORM locator.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);
        $this->setTable('users');
        $this->setPrimaryKey('id');
        $this->addBehavior('Timestamp', [
            'events' => [
                'Model.beforeSave' => [
                    'created_at' => 'new',
                    'updated_at' => 'always',
                ],
            ],
        ]);

        $this->hasMany('Cards');
        $this->hasMany('Templates');
        $this->hasMany('CardBackgrounds', ['foreignKey' => 'upload_id']);
    }

    /**
     * Default validation rules: required name, valid unique email, required callsign,
     * role enum (admin|user), and optional qth / grid_square / bio.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->scalar('name')->maxLength('name', 120)->notEmptyString('name')
            ->email('email')->notEmptyString('email')
            ->scalar('callsign')->maxLength('callsign', 20)->notEmptyString('callsign')
            ->inList('role', ['admin', 'user'])
            ->scalar('qth')->maxLength('qth', 120)->allowEmptyString('qth')
            ->scalar('grid_square')->maxLength('grid_square', 10)->allowEmptyString('grid_square')
            ->scalar('bio')->allowEmptyString('bio');

        return $validator;
    }

    /**
     * Application rules: email must be unique across all user rows.
     *
     * @param \Cake\ORM\RulesChecker $rules Rules checker instance.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->isUnique(['email']));

        return $rules;
    }
}
