<?php
/**
 * Public share landing (M2-T14).
 *
 * Anonymous-accessible page that embeds the rendered card PNG, surfaces the
 * QSO metadata, and offers PNG/PDF downloads. OG meta tags are emitted into
 * the layout's `meta` block so unfurls on chat platforms render the card
 * preview as the share image.
 *
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Card $card
 * @var array $qsoData
 * @var string $operatorCallsign
 * @var string $shareSlug
 * @var string $title
 */
$pngUrl = '/' . $card->png_path;
// Lazy PDF — built on demand by PublicController::downloadSharePdf so we
// don't store a duplicate of the card image on disk.
$pdfUrl = '/qsl/' . $shareSlug . '/download.pdf';
$absoluteCard = $this->Url->build('/qsl/' . $shareSlug, ['fullBase' => true]);
$absolutePng = $this->Url->build($pngUrl, ['fullBase' => true]);
?>

<?php $this->start('meta'); ?>
<meta property="og:title" content="<?= h($title) ?>">
<meta property="og:type" content="website">
<meta property="og:url" content="<?= h($absoluteCard) ?>">
<meta property="og:image" content="<?= h($absolutePng) ?>">
<meta name="twitter:card" content="summary_large_image">
<?php $this->end(); ?>

<h1>eQSL card from <?= h($operatorCallsign ?: '—') ?></h1>
<p>Shared eQSL — download the image or PDF below, or scroll to see the full QSO record.</p>

<img class="card-preview" src="<?= h($pngUrl) ?>" alt="eQSL card from <?= h($operatorCallsign) ?>">

<div class="d-flex gap-2 mt-4 flex-wrap">
  <a class="btn btn-primary" href="<?= h($pngUrl) ?>" download>Download image</a>
  <a class="btn btn-secondary" href="<?= h($pdfUrl) ?>">Download PDF</a>
</div>

<h2 class="h5 mt-5">QSO details</h2>
<dl class="row dl-stack">
  <dt class="col-sm-3">Confirmed by</dt><dd class="col-sm-9"><span class="callsign"><?= h($operatorCallsign ?: '—') ?></span></dd>
  <dt class="col-sm-3">For QSO with</dt><dd class="col-sm-9"><span class="callsign"><?= h($qsoData['callsign'] ?? '—') ?></span></dd>
  <dt class="col-sm-3">Date / Time UTC</dt><dd class="col-sm-9"><?= h($qsoData['qso_datetime_utc'] ?? '') ?></dd>
  <dt class="col-sm-3">Frequency</dt><dd class="col-sm-9"><?= h($qsoData['frequency_mhz'] ?? '') ?> MHz</dd>
  <dt class="col-sm-3">Band / Mode</dt><dd class="col-sm-9"><?= h($qsoData['band'] ?? '') ?> / <?= h($qsoData['mode'] ?? '') ?></dd>
  <dt class="col-sm-3">RST sent / received</dt><dd class="col-sm-9"><?= h($qsoData['rst_sent'] ?? '') ?> / <?= h($qsoData['rst_received'] ?? '') ?></dd>
</dl>

<p class="form-text mt-5">Generated by <?= h($operatorCallsign) ?> via the eQSL card generator.</p>
