<?php
/**
 * Public share landing (M2-T14).
 *
 * Anonymous-accessible page that embeds the rendered card PNG, surfaces the
 * QSO metadata, and offers PNG/PDF downloads. OG meta tags are emitted into
 * the layout's `meta` block so unfurls on chat platforms render the card
 * preview as the share image.
 *
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Card $card
 * @var array $qsoData
 * @var string $operatorCallsign
 * @var string $shareSlug
 * @var string $title
 */
$pngUrl = '/' . $card->png_path;
$pdfUrl = '/' . $card->pdf_path;
$absoluteCard = $this->Url->build('/qsl/' . $shareSlug, ['fullBase' => true]);
$absolutePng = $this->Url->build($pngUrl, ['fullBase' => true]);
?>

<?php $this->start('meta'); ?>
<meta property="og:title" content="<?= h($title) ?>">
<meta property="og:type" content="website">
<meta property="og:url" content="<?= h($absoluteCard) ?>">
<meta property="og:image" content="<?= h($absolutePng) ?>">
<meta name="twitter:card" content="summary_large_image">
<?php $this->end(); ?>

<h1>eQSL card</h1>
<img class="card-preview" src="<?= h($pngUrl) ?>" alt="eQSL card from <?= h($operatorCallsign) ?>">

<dl class="row mt-3">
  <dt class="col-sm-3">Confirmed by</dt><dd class="col-sm-9"><strong><?= h($operatorCallsign ?: '—') ?></strong></dd>
  <dt class="col-sm-3">For QSO with</dt><dd class="col-sm-9"><?= h($qsoData['callsign'] ?? '—') ?></dd>
  <dt class="col-sm-3">Date/Time UTC</dt><dd class="col-sm-9"><?= h($qsoData['qso_datetime_utc'] ?? '') ?></dd>
  <dt class="col-sm-3">Frequency</dt><dd class="col-sm-9"><?= h($qsoData['frequency_mhz'] ?? '') ?> MHz</dd>
  <dt class="col-sm-3">Band / Mode</dt><dd class="col-sm-9"><?= h($qsoData['band'] ?? '') ?> / <?= h($qsoData['mode'] ?? '') ?></dd>
  <dt class="col-sm-3">RST sent / received</dt><dd class="col-sm-9"><?= h($qsoData['rst_sent'] ?? '') ?> / <?= h($qsoData['rst_received'] ?? '') ?></dd>
</dl>

<div class="mt-3">
  <a class="btn btn-primary" href="<?= h($pngUrl) ?>" download>Download PNG</a>
  <a class="btn btn-secondary" href="<?= h($pdfUrl) ?>" download>Download PDF</a>
</div>

<p class="text-muted small mt-4">Generated by <?= h($operatorCallsign) ?> via the eQSL card generator.</p>
